config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get ':id/delete'=> 'events#destroy'
  get 'auth/:provider' => redirect("/auth/google_oauth2")
  get 'auth/:provider/callback' => 'sessions#create_with_google'
  get 'auth/failure' => redirect('/')


  resources :users , except: [:destory]
  resources :events


  resources :events do
   resources :rsvps, only: [:index]
  end

  resources :user do
   resources :events do
    resources :rsvps, only: [:new, :create]
   end
  end

  resources :rsvps, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :rsvps
  has_many :attending_users, through: :rsvps, :source => :user

  validates :name, presence: true
  validates :date, presence: true
  validates :location, presence: true
  validates :cost, presence: true
  validates :description, presence: true
  scope :todays_events,  -> {where('date == ?', Date.today) }
  scope :past_events,  -> {where('date < ?',  Date.today)}
  scope :future_events,  -> {where('date >= ?', Date.today)}
  scope :cheapest, -> {(Event.order(cost: :asc).limit(1))}
  # scope :cheapest, -> {where('cost == ?', "Free")}

  def current_rsvp
    self.rsvps.collect do |rsvp|
      rsvp.user_id
    end
  end

end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :guests, presence: true



end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  has_many :rsvps
  has_many :attending_events, :through => :rsvps, :source => :event

  validates :username, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :username, uniqueness: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def home
    if !set_user
      render :layout => "home"
    else
      redirect_to events_path
    end
  end

private

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def set_user
    @user = User.find_by_id(session[:user_id])
  end

  def logged_in?
    if !current_user #!session[:user_id]
      flash[:danger] = 'Woops! Please login or sign  up first'
      redirect_to root_path
    end
      true
  end

  def authenticated?(user)
    user.authenticate(params[:user][:password])
  end

  def owner?
    set_event && set_event.user_id == set_user.id
  end

  def set_event
    @event = Event.find_by_id(params[:event_id]) || Event.find_by_id(params[:id])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in?, only: [:new, :index, :create, :next]
  before_action :set_event, only: [:show, :edit, :update, :destroy, :next]
  before_action :set_user, only: [:new, :create, :edit, :index, :show, :next]
  before_action :authorized_to_edit?, only: [:show, :edit, :update]

  def index
    if !params[:date].blank?
      if params[:date]== 'Today Events'
        @events = Event.all.todays_events
      elsif params[:date] == 'Old Events'
        @events = Event.all.past_events
      else
        @events = Event.all.future_events
      end
    else
      @events = Event.all
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
    @event.user_id = current_user.id
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end



  def show
    @rsvps = @event.rsvps
    @user_events = @user.events
    respond_to do |format|
      format.html
      format.json {render :json => @event}
    end
  end

  def edit
  end

  def update
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event.delete
    flash[:info] = "Event has been deleted"
    redirect_to events_path
  end


private

  def event_params
    params.require(:event).permit(:name, :date, :time, :location, :cost, :description, :user_id)
  end

  def authorized_to_edit?
    if !logged_in? || !owner?
      flash[:danger] = 'You are not authorized to edit'
      redirect_to events_path
    end
      true
  end

end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :set_user, only: [:new, :create, :index, :destroy]
  before_action :logged_in?, only: [:new, :create, :index, :destroy]
  before_action :set_event, only: [:new, :create, :index]

  def new
    @rsvp= Rsvp.new
  end

  def create
    @events = Event.all
     if @event.current_rsvp.include?(@user.id)
       flash[:info] = "You've already RSVP to this event. You're all set!"
       redirect_to events_path
     end
    @rsvp = Rsvp.create(user_id: @user.id, event_id: @event.id, guests: params[:rsvp][:guests])
      if @rsvp.save
         flash[:info] = "Thanks for your RSVP"
         redirect_to events_path
      else
        render :new
    end
  end

  def index
    @rsvps = @event.rsvps
    render json: @rsvps
  end

  def destroy
    @rsvp = Rsvp.find_by_id(params[:id])
    @rsvp.destroy
    flash[:info] = "Thank you for your update"
    redirect_to events_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :layout => "home"
  end

  def create
    @user = User.find_by(username: params[:user][:username])
    if !@user || !authenticated?(@user)
      flash[:warning] = 'Oh oh - please check your username and password'
      redirect_to login_path
    else
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    end
  end

  def create_with_google
    @user = User.find_or_create_by(
      email: auth['info']['email'],
      username: auth['info']['name'],
      password_digest: auth['uid']
    )

    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  private

  def auth
   request.env['omniauth.auth']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [:show, :edit]
  before_action :set_user, only: [:show, :edit, :update]
  before_action :profile_owner?, only: [:show, :edit, :update]


  def new
    @user = User.new
    render :layout => "home"
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id]= @user.id
      redirect_to user_path(@user)
    else
      render :new, :layout => "home"
    end
  end

  def show
    @rsvps = @user.rsvps
    @user_events = user_events
    respond_to do |format|
      format.html
      format.json {render :json => @user}
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

  def profile_owner?
    if current_user.id == params[:id].to_i
      true
    else
      flash[:danger] = 'Woops - that isn\'t your profile'
      redirect_to events_path
    end
  end

  def user_events
    @user = current_user
    user_created_events = []
    Event.all.each do |event|
      if event.user_id == @user.id
        user_created_events << event
      end
    end
    user_created_events
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def dispaly_date(event)
    event.date.strftime('%B %d, %Y')
  end

  def display_time(event)
    event.time.strftime("%I:%M %p")
  end

  def future_event?(event)
    Event.all.future_events.include?(event)
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def has_events
    @user_events.size > 0
  end

  def has_rsvps
    @user.attending_events.size > 0
  end

  def future_rsvps(user)
    user.attending_events.collect do |event|
      if future_event?(event)
        event
      end
    end
  end


  def already_rsvp(user, event)
    user.attending_events.include?(event)
  end

end

app/views/application/_event_info.html.erb
  <h1><%= event.name %></h1>
  <br>
  <p><%= dispaly_date(event) %><strong> at </strong><%= display_time(event) %></p>
  <p><strong>Cost:</strong>  <%= event.cost %></p>
  <p><strong>Location:</strong>  <%= event.location %></p>
  <p><strong>Description:</strong>  <%= event.description %></p>

app/views/application/home.html.erb
<div id="title">Underground Oakland Events</div>

<div id='home'>

    <article>
      <h3><%= link_to('Log in with Google!', '/auth/google')%></h2><br>
    </article>

    <article>
      <h3><%= link_to 'Log In', login_path, {:style=>'color:#FFFFFF;'}%> </h3><br>
    </article>

    <article>
      <h3><%=link_to 'Sign Up', new_user_path, {:style=>'color:#FFFFFF;'} %></h3>
    </article>


</div>

app/views/events/_form.html.erb
<%= render "layouts/errors", object: @event %>

<%= form_for @event do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br></br>
  <%= f.label :date %>
  <%= f.date_field :date %><br></br>
  <%= f.label :time %>
  <%= f.time_field :time %><br></br>
  <%= f.label :cost %>
  <%= f.text_field :cost %><br></br>
  <%= f.label :location %>
  <%= f.text_field :location %><br></br>
  <%= f.label :description %>
  <%= f.text_area :description %><br></br>
  <%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<h1 class="center-title">Edit <%= @event.name %> </h1>

<%= render 'form' %>

app/views/events/index.html.erb
<br></br>
<div id='title'>Events in Oakland</div>
<br>

<section id="add_event_button">
  <%=link_to 'Add Event', new_event_path %>
</section>

<!--filter option -->
<div id='filter-section'>
  <div id='filter'>Filter Events:</div>
  <%= form_tag('/events', method: 'get') do %>
    <%= select_tag "date", options_for_select(['Today Events', 'Future Events', 'Old Events']), include_blank: true %>
    <%= submit_tag "Filter" %>
  <% end %>
<div>

<div class="event-container">
  <% @events.each do |event| %>

    <div class="item">
      <%= render partial: "event_info", locals: {event: event}, class: 'events' %>

      <div id="guest_for_event_<%=event.id%>"></div>
        <% if future_event?(event) && !already_rsvp(@user, event) %>
          <h3><%=link_to 'RSVP', new_user_event_rsvp_path(session[:user_id], event) %></h3>
        <% end %>


    <!--handlebars confirmed rsvp template -->

      <div class="add_rsvp_form"></div>

        <% if event.rsvps.size > 0 %>
          <%= link_to 'Guest List', event_rsvps_path(event), :class => 'show_rsvps'%>
        <% end %>

        <div id="add_guests_<%=event.id %>"></div>

    </div>  <!--end of item div  -->
  <% end %>

  <script id="rsvp_template" type="text/x-handlebars-template">
    <p>Thanks for RSVPing! You're going with {{guest}} guests.</p>
  </script>

  <script id="guests-template" type="text/x-handlebars-template">
    <ul>
      <li>{{user.username}} is attending with {{guest}} guests</li>
    </ul>
  </script>
</div><!--end of events-container div  -->


<br></br>
<br></br>
<div id="add_event "></div>

<!--new event handlebars template  -->
<script id="new_event_template" type="text/x-handlebars-template">
  <h1>{{name}}</h1>
  <h3>Date: {{displayDate}}</h3>
  <h3>Time: {{displayTime}}</h3>
  <h3>Cost: {{cost}}</h3>
  <h3>Location: {{location}}</h3>
  <h3>Description: {{description}}</h3>
  <h3><a href="user/{{user.id}}/events/{{id}}/rsvps/new">RSVP</a></h3>
</script>

<br></br>
<!-- <div id='add_event'>
  <h1>Add an Event</h1>
  <%=render  partial: "form", locals:{event: @event = Event.new}%>
<div> -->

app/views/events/new.html.erb
<section class="center-container">
  <h1>Create An Event</h1>
  <%= render 'form' %>
</section>

app/views/events/show.html.erb
  <%if @user_events[@user_events.index(@event) + 1] %>
    <%= link_to "Next Event", "/events/#{@user_events[@user_events.index(@event) + 1].id}", class: "next" %>
  <%end%>
<div class="center-container">  
  <%= render partial: "event_info", locals: {event: @event} %>
  <%= link_to 'Edit Event', edit_event_path, class: "edit_event_link"%> <br></br>
  <%= link_to 'Delete Event', event_path, method: :delete %><br></br>
</div>


<!--handlebars template  -->
<script id="event-template" type="text/x-handlebars-template">
  {{#if idOfNext}}
    <a class ="next" href="/events/{{idOfNext}}" >Next Event</a>
  {{/if}}
  <h1>{{name}}</h1>
  <h3>Date: {{displayDate}}</h3>
  <h3>Time: {{displayTime}}</h3>
  <h3>Cost: {{cost}}</h3>
  <h3>Location: {{location}}</h3>
  <h3>Description: {{description}}</h3>

  <a href="{{id}}/edit">Edit Event</a><br></br>
  <a href="{{id}}" data-method="delete">Delete Event</a><br></br>
</script>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="fields_with_errors, alert alert-danger" >
    <h2>Woops - please fix the following   <%= pluralize(object.errors.count, "error") %> before proceeding! </h2>
    <ul>
     <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
     <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_messages.erb
<% if flash[:warning] %>
  <div class="alert alert-warning">
    <%= flash[:warning] %>
  </div>
<% end %>


<% if flash[:success] %>
  <div class="alert alert-success">
    <%= flash[:sucess] %>
  </div>
<% end %>


<% if flash[:info] %>
  <div class="alert alert-info">
      <%= flash[:info] %>
  </div>
<% end %>


<% if flash[:danger] %>
  <div class="alert alert-danger">
    <%= flash[:danger] %>
  </div>
<%end%>

app/views/layouts/_messages.html.erb
<% if flash[:warning] %>
  <div class="alert alert-warning">
    <%= flash[:warning] %>
  </div>
<% end %>


<% if flash[:success] %>
  <div class="alert alert-success">
    <%= flash[:success] %>
  </div>
<% end %>


<% if flash[:info] %>
  <div class="alert alert-info">
      <%= flash[:info] %>
  </div>
<%end%>


<% if flash[:danger] %>
  <div class="alert alert-danger">
    <%= flash[:danger] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- jquery -->

    <!--bootstrap  -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Rock+Salt" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">
    <title>Underground Oakland</title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>





  <!-- Navagation bar-->
  <nav class="navbar navbar-expand-lg">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand">Underground Oakland</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" <%=link_to 'Profile', user_path(@user) %><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" <%=link_to 'Events', events_path %></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" <%=link_to 'Log Out', logout_path %> </a>
      </li>
    </ul>
  </div>
</nav>

   <%= render "layouts/messages" %>

    <!-- Content here -->

   <%= yield %>

  <!-- closing container tag -->



<!-- bootstrap plugins -->

      <script src="https://code.jquery.com/jquery-3.3.1.min.js" ></script>
      <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/1.3.0/handlebars.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <!--bootstrap  -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Rock+Salt" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">
    <title>Underground Oakland</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

  </head>
  <!-- Content here -->
  <div id="app-container">
  <body>


    <%= render "layouts/messages" %>

    <%= yield %>


<!-- bootstrap plugins -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/1.3.0/handlebars.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

 </body>
 </div>
</html>

app/views/rsvps/_rsvp_form.html.erb
<%= form_for [user, event, rsvp] do |f| %>
    <h3>Number of Guests: <%= f.number_field :guests, min: 0 %></h3>
    <%= f.submit %>
<% end %>

app/views/rsvps/index.html.erb
<h1><%= @event.name %>'s guest list </h1>

<% @rsvps.each do |rsvp| %>
  <ul>
   <li><h2><%= rsvp.user.username.titleize %> </h2>
      with <%= rsvp.guests %> guests
  </ul>
<% end %>

app/views/rsvps/new.html.erb
<section class="center-container">
  Please review and confirm your RSVP.
  <br></br>
  <%= render "layouts/errors", object: @rsvp %>
  <%= render partial: "event_info", locals: {event: @event} %>

  <%= form_for [@user, @event, @rsvp] do |f| %>
      <p>Number of Guests: <%= f.number_field :guests, min: 0 %></p>
      <%= f.submit %>
  <% end %>
</section>

app/views/rsvps/show.html.erb
<h1><%= @event.name %>'s guest list </h1>

<% @rsvps.each do |rsvp| %>
<ul>
  <li><h2><%= rsvp.user.username.titleize %> </h2>
    with <%= rsvp.guests %> guests
  </ul>
<%end%>

app/views/users/_form.html.erb
<%= render "layouts/errors", object: @user %>

<%= form_for @user, :html => {:class => "form"}  do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit :id => "submit"%>
<% end %>

app/views/users/edit.html.erb
<h1>Edit profile </h1>

<%= render 'form' %>

app/views/users/new.html.erb
<div id="title">Underground Oakland Events
  <br></br>
  Sign Up
</div>
<%= render 'form' %>

app/views/users/show.html.erb
<div id="profile-title"><%=@user.username.titleize%></div>

<section id="profile-container">

  <div id=user-info>

    <p class='dashboard'>Your dashboard</p>
    <% if has_events %>
        <h2>You have posted <%=pluralize(@user_events.size, 'event')%></h2>
      <% else %>
        <h2>You haven't posted any events yet.</h2>
    <% end %>

    <div class="events_display">
      <% @user_events.each do |event| %>
        <p id="event"><%= link_to "#{event.name}", event_path(event) %></p>
      <% end %>
    </div>

  </div> <!--end user info-->

  <!--handlebars show event template  -->
  <script id="ordered-events-template" type="text/x-handlebars-template">
    <p><a href="/events/{{id}}">{{name}}</a></p>
  </script>

  <!-- refractor attending events and pluralize-->
  <div id="user-rsvp">
    <% if future_rsvps(@user).size > 0 %>
      <h2 class='user-title'> You are attending <%= pluralize(@user.attending_events.size, 'event') %></h2>
    <% end %>

    <% future_rsvps(@user).each do |event| %>
      <div id='rsvp'>
        <p class='event'><%= event.name %></p>
          <div id="rsvp_details">
            <p>on <%= dispaly_date(event) %></p>
            <p>at <%=display_time(event)%></p>
            <% event.rsvps.each do |rsvp| %>
              <% if rsvp.user_id == @user.id %>
                <p><%= button_to 'Cancel RSVP', rsvp_path(rsvp), method: :delete %></p>
              <% end %>
            <% end %>
          </div>
      </div><!--rsvp_details-->
    <% end %>
  </div> <!--user-rsvp-->

</section> <!-- end profile container -->
<br></br>
<div class="edit_link">
  <%= link_to 'Edit Profile', edit_user_path(@user)%>
</div>